config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book), notice: "Book was successfully created."
    else
    render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
    redirect_to book_path(@book), notice: "Book was successfully updated."
    else
    render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div class="errors">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model:@book, local: true do |f| %>
  <div class="field">
    <div>Title</div>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <div>Body</div>
    <%= f.text_area :body %>
  </div>
  <div class="actions"><%= f.submit "Update Book" %></div>
  <div class="link"><%= link_to "Show", book_path(@book.id) %></div>
  <div class="link"><span>|</span></div>
  <div class="link"><%= link_to "Back", books_path %></div>
<% end %>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <mate charset="UTF-8">
        <link rel="stylesheets" href="books.scss">
        <title>WebCampBackendNew</title>
    </head>
    <body>
        <h1>Books</h1>
        <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Body</th>
                <th></th>
            </tr>
        </thead>

            <tbody>
                <% @books.each do |book| %>
                    <tr>
                    <td><%= book.title %></td>
                    <td><%= book.body %></td>
                    <td><%= link_to "Show", book_path(book.id) %></td>
                    <td><%= link_to "Edit", edit_book_path(book.id) %></td>
                    <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <h2>New book</h2>
            <% if @book.errors.any? %>
                <div class="errors">
                    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
                        <ul>
                        <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                        </ul>
                </div>
            <% end %>
        <%= form_with model:@book,  local:true do |f| %>
            <div class="field">
                <div>Title</div>
                <%= f.text_field :title %>
            </div>
            <div class="field">
                <div>Body</div>
                <%= f.text_area :body %>
            </div>
            <div><%= f.submit "Create Book" %></div>
        <% end %>
    </body>
</html>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model:@book, url:"/books", local:true do |f| %>
<h4>title</h4>
<%= f.text_field :title %>
<h4>body</h4>
<%= f.text_area :body %>
<%= f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
<p class="notice"><%= notice %></p>
<p><strong>Title:</strong><%= @book.title %></p>
<p><strong>Body:</strong><%= @book.body %></p>
<!--editのリンク-->
<div class="link"><%= link_to "Edit", edit_book_path(@book) %></div>
<div class="link"><span>|</span></div>
<div class="link"><%= link_to "Back", books_path %></div>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheets" href="homes.scss">
    <title>WebCampBackendNew</title>
  </head>
  <body>
    <h1>ようこそ <strong>Bookers</strong> へ！</h1>
    <p>
      <strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
    </p>
    <p>印象を共有し交換することができます</p>
    <p>
      <!--startのカーソルに乗ったら黒くしたい-->
      <%= link_to "start", books_path %>
    </p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>